### PR TITLE
CSV parser to satisfy the RFC4180 standard.

### PR DESCRIPTION
**Pull request by brandones**
The default CSV Parser used by OpenCSV does not satisfy the CSV standard, RFC4180. It handles escape characters incorrectly. Because of this, OpenCSV also offers a CSV parser called RFC4180Parser. This is the correct parser to use.

### CODE REVIEW

**Comment by brandones** [comment]
Whoops, need to fix the build...

**Comment by brandones** [comment]
Like, that OpenCSV might provide some utilities for validating CSV files? I wouldn't know, but it might be worth looking into.

Please wait to merge this until I fix the PIT test file, which is presently backlash-escaped.

**Comment by brandones** [comment]
Ok, this is ready.

**Review by mks-d — COMMENTED** [review]
@brandones wondering if we still want this to get in? If yes I will have to ask you to rebase.

**Comment by brandones** [comment]
Hi @mks-d , yes I think that would be great. No practical need for PIH any more, but I'm sure standard compliance will save others the same pain down the line.

**Review by ibacher — APPROVED** [review]
LGTM

**Comment by brandones** [comment]
:tada:

**Comment by mogoodrich** [comment]
@ibacher  @brandones  can we revert these changes, at least temporarily?  PIH right now relies on the latest snapshot of initializer and this happens to break the PIH EMR... not sure exactly what the issue is, and happy to look into it further, but the timing is bad since we are trying to get a release out the door tomorrow.

Thanks!

For reference, here's the error I'm seeing when we start up the PIH EMR (if there's a ticket/issue related, I can add that in as well).

`ARN - InitializerSetup.loadPreConceptDomains(49) |2022-04-20 23:26:11,220| Loading from Initializer: conceptsources
Exception in thread "Thread-10" java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.countMatches(Ljava/lang/CharSequence;C)I
	at com.opencsv.RFC4180Parser.hasOnlyOneQuote(RFC4180Parser.java:192)
	at com.opencsv.RFC4180Parser.lastElementStartedWithQuoteButDidNotEndInOne(RFC4180Parser.java:184)
	at com.opencsv.RFC4180Parser.splitWhileNotInQuotes(RFC4180Parser.java:173)
	at com.opencsv.RFC4180Parser.parseLine(RFC4180Parser.java:121)
	at com.opencsv.AbstractCSVParser.parseLineMulti(AbstractCSVParser.java:64)
	at com.opencsv.CSVReader.readNext(CSVReader.java:376)
	at org.openmrs.module.initializer.api.CsvParser.fetchNextLine(CsvParser.java:277)
	at org.openmrs.module.initializer.api.CsvParser.getLines(CsvParser.java:172)
	at org.openmrs.module.initializer.api.loaders.BaseCsvLoader.load(BaseCsvLoader.java:91)
	at org.openmrs.module.initializer.api.loaders.BaseInputStreamLoader.load(BaseInputStreamLoader.java:39)
	at org.openmrs.module.initializer.api.loaders.BaseCsvLoader.preload(BaseCsvLoader.java:72)
	at org.openmrs.module.initializer.api.loaders.BaseFileLoader.preload(BaseFileLoader.java:51)
	at org.openmrs.module.initializer.api.loaders.BaseFileLoader.lambda$loadUnsafe$1(BaseFileLoader.java:82)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.openmrs.module.initializer.api.loaders.BaseFileLoader.loadUnsafe(BaseFileLoader.java:83)
	at org.openmrs.module.pihcore.setup.InitializerSetup.loadPreConceptDomains(InitializerSetup.java:51)
	at org.openmrs.module.pihcore.setup.ConfigurationSetup.configureNonConceptDependencies(ConfigurationSetup.java:166)
	at org.openmrs.module.pihcore.PihCoreActivator.configureSystem(PihCoreActivator.java:50)
	at org.openmrs.module.pihcore.PihCoreActivator.started(PihCoreActivator.java:40)
	at org.openmrs.module.ModuleUtil.refreshApplicationContext(ModuleUtil.java:928)
	at org.openmrs.module.web.WebModuleUtil.refreshWAC(WebModuleUtil.java:854)
	at org.openmrs.web.Listener.performWebStartOfModules(Listener.java:633)
	at org.openmrs.web.Listener.performWebStartOfModules(Listener.java:613)
	at org.openmrs.web.Listener.startOpenmrs(Listener.java:252)
	at org.openmrs.web.WebDaemon$1.run(WebDaemon.java:42)
`

**Pull request merged**
