### PR TITLE
[#198] Reloading Concept CSVs should not clear Member and Answers if …

### PR DESCRIPTION
**Pull request by mogoodrich**
…those columns aren't in the CSV

### CODE REVIEW

**Review by mseaton — APPROVED** [review]
This looks good to me - regardless of what other improvements we might make in the future, I think this is the right thing to do.  However, as things are starting to get rather complex with various types of metadata affected my multiple iniz domains, I think more discussion is needed overall as to how we approach this.  We can discuss outside of this ticket.

**Comment by mogoodrich** [comment]
Just pinging you on this one to take a look when you get a chance @ibacher ... thanks!

**Review by Ruhanga — APPROVED** [review]

**Comment by mogoodrich** [comment]
Just another ping @ibacher ... :)  fyi @mseaton if you want

**Comment by mseaton** [comment]
@mogoodrich I think we are likely good to merge this, but can you push an update to the concepts.md file in the readme that documents the behavior for the members and answers?  eg. describe that - if the columns are present, this will clear any existing members and answers and add those specified.  If the columns are not present, it will not change any existing relationships?

**Comment by mogoodrich** [comment]
Fair enough @mseaton , will do.

**Review by ibacher — COMMENTED** [review]
LGTM

**Review by ibacher — APPROVED** [review]

**Comment by mogoodrich** [comment]
@mseaton documentation updated

**Pull request merged**
